### ISSUE TITLE
Question: Old version help

### ISSUE THREAD

**Issue by oleteacher** [alexsky177/chat#4]
We setup your older version for classroom use: https://github.com/alexsky177/chat/tree/chatgpt

I see you no longer updating it, so have a few questions please:

1) What function does the "Web Access" toggle have?

2) Do all the different models actually work without changing the end point url?

I assume all the other settings work?

This is really easy for younger students to use and really like to keep using.

Thanks for your time.

**Comment by alexsky177** [comment]
1) "Web Access" changed theme to dark or light
2) Tested models: 
gpt-3.5-turbo
gpt-3.5-turbo-0301
gpt-3.5-turbo-0613
gpt-3.5-turbo-16k
Also use new version:
https://github.com/alexsky177/chat

**Comment by oleteacher** [comment]
Ok, thank you. Love to use the new version but in school environment, it can take months to get approval to run scripts like this. We just got approval to run your old version after wafting some time , lol.

Anyway, thanks for reply and sharing your work.
