### ISSUE TITLE
Copy button not working

### ISSUE THREAD

**Issue by oleteacher** [alexsky177/chat#5]
Trying to ready your newest version so can submit it to our IT department for approval to run on school server.

Just noticed that the "Copy" button does not work. Have not found way to make the copy button work, do you have ideas? This is what I see:

![image](https://github.com/alexsky177/chat/assets/26278259/65082c3e-c8d8-43a6-8277-9c94b3016b8f)

**Comment by alexsky177** [comment]
I tested om my we server. It is work.
This button only copies the code in the highlighted area, not the entire response.

**Comment by alexsky177** [comment]
I also see that you are using a tablet or other mobile device. That's the whole reason. The "Copy" button only works on a computer or laptop.

**Comment by oleteacher** [comment]
Yes, I understand it is designed to only copy code area.

Not using mobile or tablet. Had browser resized because using two different browser in testing.

Moved to a different server and now the copy button working. Very strange it did not work on first server; they are basically identical.

Sorry for the false alarm:) Thanks for reply!
